#!/usr/bin/env python3
# encoding=UTF-8

# Copyright © 2012-2022 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

import argparse

import linuxvt

0_0  # Python >= 3.6 is required

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('-t', '--tty', metavar='/dev/ttyN')
    parser.add_argument('-v', '--vcsa', metavar='/dev/vcsaN')
    parser.add_argument('-f', '--format', choices=('plain-text', 'ansi-text', 'xhtml'), default='plain-text')
    options = parser.parse_args()
    with linuxvt.VT(options.tty, options.vcsa) as vt:
        peek = getattr(vt, 'peek_' + options.format.replace('-', '_'))
        print(peek(), end='')

if __name__ == '__main__':
    main()

# vim:ts=4 sts=4 sw=4 et
