name: CI
on:
- push
- pull_request
jobs:
  main:
    strategy:
      matrix:
        include:
        - python: '3.6'
          os: ubuntu-20.04
        - python: '3.7'
          os: ubuntu-20.04
        - python: '3.8'
          os: ubuntu-20.04
        - python: '3.9'
          os: ubuntu-20.04
        - python: '3.10'
          os: ubuntu-22.04
        - python: '3.11'
          os: ubuntu-22.04
        - python: '3.12-dev'
          os: ubuntu-22.04
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v4
    - name: set up Python ${{matrix.python}}
      uses: actions/setup-python@v4
      with:
        python-version: ${{matrix.python}}
    - name: run pydiatra
      run: |
        python -m pip install pydiatra
        python -m pydiatra -v .
    - name: run pyflakes
      run: |
        python -m pip install pyflakes
        python -m pyflakes .
    - name: run tests
      run: |
        prove -v
    - name: check README syntax
      run: |
        python3 -m pip install restructuredtext-lint pygments
        rst-lint --level=info --encoding=UTF-8 README

# vim:ts=2 sts=2 sw=2 et
